export const Images = {
  checkIcon: require("../resources/checkedIcon.png"),
  unCheckedIcon: require("../resources/unCheckedIcon.png"),
  eyeIcon: require("../resources/eyeIcon.png"),
  weekMealsLogo: require("../resources/logo.png"),
  onBoardingIcon1: require("../resources/Icon1.png"),
  onBoardingIcon2: require("../resources/Icon2.png"),
  onBoardingIcon3: require("../resources/Icon3.png"),
  onBoardingIcon4: require("../resources/Icon4.png"),
  editIcon: require("../resources/editIcon.png"),
  profileImage: require("../resources/profileImage.png"),
  completeProfileCover: require("../resources/completeProfileCover.png"),
  welcomeCover: require("../resources/welcomeCover.png"),
  avatar: require("../resources/avatar.png"),
  dumbbell: require("../resources/dumbbell.png"),
  bikeworkout: require("../resources/bikeworkout.png"),
  backArrow: require("../resources/backArrow.png"),
  crossIcon: require("../resources/crossIcon.png"),
  food1: require("../resources/food1.png"),
  food2: require("../resources/food2.png"),
  food3: require("../resources/food3.png"),
  food4: require("../resources/food4.png"),
  food5: require("../resources/food5.png"),
  food6: require("../resources/food6.png"),
  infoIcon: require("../resources/infoIcon.png"),
  addIcon: require("../resources/addIcon.png"),
  optionDotIcon: require("../resources/optionDotIcon.png"),
  downArrow: require("../resources/downArrow.png"),
  deleteIcon: require("../resources/deleteIcon.png"),
  additionIcon: require("../resources/additionIcon.png"),
  subtractIcon: require("../resources/subtratIcon.png"),
  calendarIcon: require("../resources/calendarIcon.png"),
  meditationIcon: require("../resources/meditationIcon.png"),
  switchButton: require("../resources/switchButton.png"),
  bellIcon: require("../resources/bellIcon.png"),
  calendarCheckIcon: require("../resources/calendarCheckIcon.png"),
  checkedCircle: require("../resources/checkedCircle.png"),
  unCheckedCircle: require("../resources/unCheckedCircle.png"),
  fatCheckImage1: require("../resources/fatCheckImage1.png"),
  fatCheckImage2: require("../resources/fatCheckImage2.png"),
  fatCheckImage3: require("../resources/fatCheckImage3.png"),
  fatCheckImage4: require("../resources/fatCheckImage4.png"),
  fatCheckImage5: require("../resources/fatCheckImage5.png"),
  fatCheckImage6: require("../resources/fatCheckImage6.png"),
  fatCheckImage7: require("../resources/fatCheckImage7.png"),
  editPenCircle: require("../resources/editPenCircle.png"),
  breakfastImage1: require("../resources/breakfastImage1.png"),
  breakfastImage2: require("../resources/breakfastImage2.png"),
  breakfastImage3: require("../resources/breakfastImage3.png"),
  breakfastImage4: require("../resources/breakfastImage4.png"),
  breakfastImage5: require("../resources/breakfastImage5.png"),
  lunchImage1: require("../resources/lunchImage1.png"),
  lunchImage2: require("../resources/lunchImage2.png"),
  lunchImage3: require("../resources/lunchImage3.png"),
  lunchImage4: require("../resources/lunchImage4.png"),
  lunchImage5: require("../resources/lunchImage5.png"),
  dinnerImage1: require("../resources/dinnerImage1.png"),
  dinnerImage2: require("../resources/dinnerImage2.png"),
  dinnerImage3: require("../resources/dinnerImage3.png"),
  dinnerImage4: require("../resources/dinnerImage4.png"),
  dinnerImage5: require("../resources/dinnerImage5.png"),
  watchIcon: require("../resources/watchIcon.png"),
  searchIcon: require("../resources/searchIcon.png"),
  rightIcon: require("../resources/rightIcon.png"),
  loadMoreIcon: require("../resources/loadMoreIcon.png"),
  nextCircledIcon: require("../resources/nextCircledIcon.png"),
  categoryCarouselImage1: require("../resources/categoryCarouselImage1.png"),
  categoryCarouselImage2: require("../resources/categoryCarouselImage2.png"),
  categoryCarouselImage3: require("../resources/categoryCarouselImage3.png"),
  categoryCarouselImage4: require("../resources/categoryCarouselImage4.png"),
  crossCircleWhite: require("../resources/crossCircleWhite.png"),

  



};
